name = input('Enter your Character Name: ')
character_class = input('Enter your Character Class:')
realm = input('Enter your Home Realm:')
chosen_weapon = input ('Enter your Chosen Weapon:')
special_ability = input('Enter your Special Ability:')
print('=============================================')
print('      -- CHARACTER CREATION COMPLETE --        ')
print('Name:             ', name)
print('Class:            ', character_class)
print('Realm:            ', realm)
print('Title: ', name , 'the', character_class , "of", realm)
print('\n----------------------------------------------')
print('Weapon of Choice:   ', chosen_weapon)
print('Special_Ability:    ', special_ability)
print('=============================================')
